### ISSUE TITLE
Generic Inference

### ISSUE THREAD

**Issue by Checkmate50** [cucapra/linguine#20]
Writing `normalize<model>(v)` is super annoying (especially when translating from glsl code).  It would be nice if we could instead write `normalize(v)` and have the compiler infer the parameter type from the type of `v`.  

Note that this is non-trivial; we should have, for instance, that `t1 v1; t2 v2; dot(v1, v2)` has type `t1` if `t2<=t1`.  It would also be nice to give an error if the user attempts `vec3 v1; t1 v2; dot(v1, v2)`, since these two vectors are not of the same 'space'.  The strictness property imposed by the semantics should be sufficient for this, but it's worth being aware of / designing around.

**Comment by sampsyo** [comment]
Hey, it looks like some Markdown fiddling could be in order in the second paragraph there!

A while back, I recommended a simple, non-fancy way to approach this kind of limited inference that might be fine for the majority of cases: in a function ``f<`t>(`t x, ...)``, where the type of one of the parameter is *exactly* the type parameter, then unification is easy. This is the case with `normalize` and `dot`, for example. The typechecker would look at the first parameter, see if its type is a type parameter, and if so conclude (soundly!) that the parameter must bind to the type of the argument. Then continue checking the rest of the arguments while substituting the type parameter for that type to ensure a consistent match. One advantage of this approach is that it's "greedy," in that it never "changes its mind" after assigning the type variable the first time.

To be clear, this approach will *not* be able to infer the parameter for a function whose type is like ``f<`t>(hom<`t> x, ...)``, i.e., when the parameter type is not exactly a type parameter but contains one. But I expect that to be rarer.
