### ISSUE TITLE
Code Insertion With Tag Coord

### ISSUE THREAD

**Issue by Checkmate50** [cucapra/linguine#26]
As a proposal, let `tag` declarations be extended with the qualifier `coord`, indicating that the given tag actually represents a coordinate system with a defined basis.  Since this basis is well-defined, there exists exactly one linear transformation between two coordinate systems `a` and `b`, which has the type `a->b`.  The typechecker will thus only accept programs with exactly one transformation of this type; however, this transformation will be loaded into a context and can be inserted automatically into other code.

Given coordinate systems `a` and `b` with a vector `v` in `a` and the transformation matrix `m` in our context, the syntax `v in b` will be replaced at compile time with the code `m * v`.  Note that transformations can be chained together (e.g. `a->b` and `b->c` allows transformation to `a->c`).  I propose that our type system handles this by allowing a user to declare a matrix of the combined type (like type `a->c` in the example), so long as it has not been put together in the context already through a use of `in`.

**Comment by sampsyo** [comment]
Cool!

> I propose that our type system handles this by allowing a user to declare a matrix of the combined type (like type a->c in the example), so long as it has not been put together in the context already through a use of in.

It sounds like, with this design, the `in`-resolver mechanism has no additional "work" to do to use transformation composition. That is, it doesn't have to do any fancy shortest-path search through the graph of available transformations—it only has to use the *pre-declared* one-step transformation that the user has already conjured into existence, right?

That is certainly simpler, but I also wonder if people wouldn't also find it helpful to fill in those multi-hop transformations automatically. I suppose this is a question to be answered by example.

**Comment by sampsyo** [comment]
You also explained the above to me in person! The upshot is that you *do* want to support multi-hop transformations; you just want to have the effect of inserting all the declarations so they can be reused later in the scope.

My proposed roadmap:

- [ ] Version 1.0: Single-hop only.
- [ ] Version 2.0: Multi-hop, but no "saving" of composed transformations. The matrix multiplications get recomputed every time.
- [ ] Version 3.0: Actually save and reuse the composed transformations. This would just be for efficiency; the capabilities and results should be the same as in 2.0.

**Comment by Checkmate50** [comment]
Version 2.0 added and tested with all current features.  I will leave this issue open as a reference for future efficiency modifications.

**Comment by Checkmate50** [comment]
As an update to this issue, 'in' expressions are explained with more generality in the wiki at https://github.com/cucapra/linguine/wiki/Tutorial:-Casting-and-In-Expressions

**Comment by Checkmate50** [comment]
No longer a requirement with the changes from Linguine to Gator
