### ISSUE TITLE
Variable Tag Types

### ISSUE THREAD

**Issue by Checkmate50** [cucapra/linguine#27]
Linguine needs the introduction of variable tags, such as tags of the form `hom<model>`.  These must be tags declared when forming the delta context.  I propose that the syntax ``tag par<`t : vec3> is `t`` create the tag `par` with a parametrization requirement of `vec3`, which is a child of the parametrizing tag.  A user can, of course, parametrize with a parametrized tag (e.g. `par<par<model>>` is a valid tag).

**Comment by sampsyo** [comment]
Hmm, I'm not quite sure I understand this one… is the problem with the current system that `par<foo>` cannot be a subtype of `foo`? (If so, is `norm` the motivation here? It seems like `hom<model>` need not be a subtype of `model`.)

**Comment by sampsyo** [comment]
For `hom`, I assume this would look like:

    tag hom<`t : vecN> is vecM

for some N and M, namely 3 and 4 (probably).

**Comment by Checkmate50** [comment]
Feature added and tested in latest development branch pull!
