### ISSUE TITLE
Lost parentheses

### ISSUE THREAD

**Issue by Checkmate50** [cucapra/linguine#34]
`1.0 / (256.0 * (256.0 * 256.0))` compiles to `1.0 / 256.0 * 256.0 * 256.0` since we don't track parentheses.  This seems worth fixing!

**Comment by sampsyo** [comment]
Indeed; this does seem worth fixing! FWIW, the straightforward way to deal with this does not require preserving the original parentheses in the source code (i.e., adding metadata to the AST or even a new kind of AST node to represent the parens). Instead, we can just conservatively over-insert parentheses when emitting the code to preserve the shape of the parentheses-free AST.
