### ISSUE TITLE
Pretty Printing Flag

### ISSUE THREAD

**Issue by Checkmate50** [cucapra/linguine#36]
The linguine compiler emits glsl code as a single line string for easy conversion to a JavaScript friendly string.  Unfortunately, JavaScript-friendly is not human-friendly, making understanding and debugging the resulting glsl code tricky.

It would be nice to add some pretty printing functionality to the emitter and an associated flag (-p?  --pretty-printing?).  Something as simple as newlines after each semicolon and curly brace would probably be sufficient (maybe extra lines between function declarations as well?)

**Comment by sampsyo** [comment]
Seems like a good idea to me! And probably not too hard to add—it would just require a bit of nastiness tracking the amount of indentation to put everywhere.

**Comment by Checkmate50** [comment]
Resolved by #100
