### ISSUE TITLE
Allow global variables to be defined after functions in the global scope

### ISSUE THREAD

**Issue by Chillee** [cucapra/linguine#44]
For example, take
```
...
tag coord hom<`t : vec3> is vec4;
tag norm<`t : vec> is `t;

declare vec4 vec4(vec3 v, float f);
declare vec3 vec3(vec4 v);

canon hom<`t> homify<`t : vec3>(`t v) { return vec4(v as vec3, 1.) as hom<`t>; }
canon `t hom_reduce<`t : vec3>(hom<`t> v) { return vec3(v as vec4) as `t; }

attribute model aPosition;
uniform hom<model>->hom<world> uModel;
uniform hom<world>->hom<view<camera>> uCamera;
uniform hom<view<camera>>->hom<proj<camera>> uProjection;
uniform hom<world>->hom<view<light>> uLightView;
uniform hom<view<light>>->hom<proj<light>> uLightProjection;

void main() {
 ....
```
This is likely to be how we'd like to write it. Functions like `homify` are essentially "library code", and as such, we'd like to have the freedom to put the global variables close to where we'd use them.

As of now, we need to write
```
...
tag coord hom<`t : vec3> is vec4;
tag norm<`t : vec> is `t;

declare vec4 vec4(vec3 v, float f);
declare vec3 vec3(vec4 v);

attribute model aPosition;
uniform hom<model>->hom<world> uModel;
uniform hom<world>->hom<view<camera>> uCamera;
uniform hom<view<camera>>->hom<proj<camera>> uProjection;
uniform hom<world>->hom<view<light>> uLightView;
uniform hom<view<light>>->hom<proj<light>> uLightProjection;

canon hom<`t> homify<`t : vec3>(`t v) { return vec4(v as vec3, 1.) as hom<`t>; }
canon `t hom_reduce<`t : vec3>(hom<`t> v) { return vec3(v as vec4) as `t; }

void main() {
 ....
```

Currently, we get a parse error if we do the first one.

**Comment by yinnonsanders** [comment]
Sounds reasonable, the only issue I can think of is that the way the semantics currently works, the global variables could be used in any of the methods, so a variable could be used before its declaration appears in the file. Fixing the semantics to avoid that could get relatively complicated.

**Comment by sampsyo** [comment]
Makes sense to me! As @Chillee said, it makes sense to think of functions like `homify` and `hom_reduce` as part of a "standard library." Given an eventual module/import mechanism, the entire first few stanzas could be moved to a different file.
