### ISSUE TITLE
Get CircleCI working again

### ISSUE THREAD

**Issue by euisuny** [cucapra/linguine#47]
`test.py` passes (prints `No 👏 Failures 👏`) on local machines but CircleCI hasn't been in compliance with it for a little while.

Seems to be failing only on "failure tests" that are not checking for parsing errors.

Possibly a formatting error in the test script and/or the failing test files.
(Tried removing trailing spaces, replacing every instance of `\r\n` to `\n` but did not work.)

**Comment by Checkmate50** [comment]
Fixed in a recent commit
