### ISSUE TITLE
Add Support for Generic Declare Statements for GLSL Functions

### ISSUE THREAD

**Issue by pauljoo28** [cucapra/linguine#80]
Currently most if not all generic declare statements do not parse in `/test-u/generics`.

**Comment by Checkmate50** [comment]
All of these are using the old Linguine style of generic declarations!  However, I do agree with the need for existential types in Gator -- see my response to #81.

To fix the need for parsing, simply change all instances of `<'t extends "type">` to `with "type" T`.  For example, in `tagw_inference.lgl`, we would change:

```
vec2 to_top<`t extends vec2>(`t x) {
    `t->vec2 m = [[1., 0.], [0., 1.]];
    return m * x;
}
```

To:

```
with vec2 T:
float[2] to_top(T x) {
    mat2x2 m = [[1., 0.], [0., 1.]];
    return m * x;
}
```
