### ISSUE TITLE
Strictly Subtyped Parameterization

### ISSUE THREAD

**Issue by Checkmate50** [cucapra/linguine#84]
At the moment, we support parameterization of the form:

```
with float T:
declare T foo(T v);
```

However, it would be helpful if we could have a rule that a function only applies to every subtype of the given type except the type itself; that is, a strict less than rather than a less than or equal too.  I imagine behavior of the following form:

```
type scalar is float;
with T < float:
declare T max(T v);
scalar x = 5.;
float y = 6.;
print max(x); // typechecks
print max(y); // fails to typecheck
```

**Comment by sampsyo** [comment]
Sounds cool, but just for completeness, why would this be useful? Without thinking about it too hard, it seems mainly useful for the case you've shown here (excluding our "untagged" top types, like float), but even then I can't quite come up with an example function that would want to exclude them…

**Comment by Checkmate50** [comment]
Thanks for catching me on being lazy with explaining this issue!  The main intention of this feature is to support dimensional analysis eventually.  We want types to support operations without the same core issue faced by geometry types: information can always be lost by going to the "top" type and ignoring the underlying types used.  Instead, we want something like the following:

```
type meter is float;
type second is float;
with T < float:
declare T +(T x, T y);

meter x = 5.;
second y = 5.;
auto result = x + y; // Gives an error, as expected
```

There are probably similar use cases I'm not thinking of, but this is the main intention.

**Comment by sampsyo** [comment]
Aha, ye olde "strictness condition"! Thanks for the extra context.
